<a href="https://colab.research.google.com/github/Ramjidixit/ML_lab/blob/main/RandomForestAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris

In [7]:
#load the iris dataset
iris=load_iris()
x=iris.data
y=iris.target

In [8]:
#split the data into training and testing sets
#split the dataset into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
#initialize the Random Forest Classifier
rf_classifier=RandomForestClassifier(n_estimators=100,random_state=42)


In [10]:
#train the model
rf_classifier.fit(x_train,y_train)

#make predictions on the test set
y_pred=rf_classifier.predict(x_test)

In [11]:
#evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix=confusion_matrix(y_test, y_pred)
classification_rep=classification_report(y_test, y_pred)

In [12]:
#print the ewsults
print(f"Accuracy:{accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy:1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

